name: Rocky World Utils CI

on: [push, pull_request]

jobs:
  Build-and-Test:
    name: Build Python - ${{ matrix.python-version }}
    runs-on: "ubuntu-latest"
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.11','3.12']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pycodestyle
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Code Style Check
      run: |
        pycodestyle --ignore=E501,E505,W503 rocky_worlds_utils/*.py
    - name: Install Rocky Worlds Utils
      run: |
        pip install .
    - name: Test with pytest
      run: |
        pytest
